version: "3.8"

services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    restart: always
    volumes:
      - ./frps.toml:/etc/frp/frps.toml
    ports:
      - "7000:7000" 
