serverAddr = "203.31.40.13"
serverPort = 7000

auth.method = "token"
auth.token = "my_secure_token"

# [[proxies]]
# name = "app1"
# type = "tcp"
# localIP = "127.0.0.1"
# localPort = 4001
# remotePort = 4001



[[proxies]]
name = "app1"
type = "http"
localIP = "127.0.0.1"
localPort = 4001
subdomain = "app1"
